targets:
  $default:
    builders:
      svg2dart:
        enabled: true
        options:
          input: 'assets/svg'
          output: 'lib/generated/icons'
          convertTo: 'customPainter'
          optimizations: false