targets:
  $default:
    builders:
      svg2dart:
        enabled: true
        options:
          input: "assets/asd"
          output: "lib/sdf"


builders:
  svg2dart:
    import: "package:svg2dart/svg2dart.dart"
    builder_factories: ["svg2dartBuilder"]
    build_extensions: { "$package$": [".dart"] }
    auto_apply: root_package
    build_to: source