name: svg2dart
description: A command-line tool to convert SVG files into pure Dart code for Flutter.
version: 0.0.6
homepage: https://github.com/dened/svg2dart 
repository: https://github.com/dened/svg2dart
issue_tracker: https://github.com/dened/svg2dart/issues

executables:
  svg2dart:

topics:
  - svg
  - flutter
  - code-generation
  - widget

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  build: ^4.0.0
  dart_style: ^3.1.2
  meta: ^1.16.0
  path: ^1.9.1
  vector_graphics_codec:  ^1.1.13 
  vector_graphics_compiler:  ^1.1.19

dev_dependencies:
  build_runner: ^2.8.0 
  build_test: ^3.4.0 
  lints: ^6.0.0 
  test: ^1.26.3

