name: Setup Dart
description: Sets up the Dart environment

inputs:
  dart-version:
    description: "The version of Dart to use"
    required: false
    default: "stable"

runs:
  using: composite
  steps:
    - name: 🚂 Setup Dart
      uses: subosito/flutter-action@v2
      with:
        channel: "${{ inputs.dart-version }}"